[package]
name = "mdsRust"
version = "0.1.0"
authors = ["MatthieuDev"]
description = "2d mds with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.48"